pipelines:
  create_directory_pipeline:
    group: example_group
    label_template: "${COUNT}"
    materials:
      git:
        url: https://github.com/nayan-tank/gocd.git
        branch: main
    stages:
      - name: create_directory_stage
        jobs:
          - name: create_directory_job
            resources:
              - linux
            tasks:
              - exec:
                  command: mkdir
                  arguments:
                    - -p
                    - /home/linux/new-directory
