pipelines:
  create_file_pipeline:
    group: example_group
    label_template: "${COUNT}"
    materials:
      git:
        url: https://github.com/nayan-tank/gocd.git
        branch: main
    stages:
      - create_file_stage:
          jobs:
            - create_file_job:
                resources:
                  - windows
                tasks:
                  - exec:
                      command: powershell
                      arguments:
                        - -Command
                        - |
                          New-Item -Path C:\temp\example.txt -ItemType File -Force
