environments:
  production:
    pipelines:
      - my_pipeline
    environment_variables:
      APP_ENV: staging

pipelines:
  my_pipeline:
    group: default
    label_template: '${COUNT}'
    lock_behavior: none
    materials:
      git_repo:
        type: git
        url: https://github.com/nayan-tank/gocd.git
        branch: main
        destination: gocd
    stages:
      - name: file
        clean_workspace: true
        jobs:
          - name: create_file
            resources:
              - windows
            tasks:
              - exec:
                  command: powershell
                  arguments:
                        - -Command
                        - |
                          New-Item -Path C:\temp\example.txt -ItemType File -Force
